development:
  adapter: postgresql
  encoding: unicode
  database: spree_dev
  pool: 5
  username: spree
  password: spree

test:
  adapter: postgresql
  encoding: unicode
  database: spree_test
  pool: 5
  username: spree
  password: spree

production:
  adapter: postgresql
  encoding: unicode
  database: spree_prod
  pool: 5
  username: spree
  password: spree
